FROM python:3.7

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install git

WORKDIR /conf
COPY config.ini /conf/

WORKDIR /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
RUN chmod +x leaf-mqtt.py

ENTRYPOINT ["python", "leaf-mqtt.py"]
